#!/usr/bin/env bash
# Concatenates every migration into one file you can paste into the Supabase
# SQL editor in a single go, instead of opening 15 files by hand.
#
# Usage: ./scripts/bundle-migrations.sh <project-ref> [webhook-secret] > setup.sql
#
# <project-ref> is the subdomain of your Supabase URL:
#   https://abcdefgh.supabase.co  ->  abcdefgh
# It is substituted into the push-notification triggers (0007, 0008), which
# otherwise post to a placeholder host.
set -euo pipefail
cd "$(dirname "$0")/.."

REF="${1:?usage: bundle-migrations.sh <project-ref> [webhook-secret]}"
SECRET="${2:-$(head -c 24 /dev/urandom | base64 | tr -d '/+=' )}"

echo "-- Pisga — every migration, in order, as one script."
echo "-- Generated by scripts/bundle-migrations.sh for project: $REF"
echo "-- Webhook secret used in the push triggers: $SECRET"
echo "-- (set the same value as a secret named WEBHOOK_SECRET on the Edge Functions)"
echo

for migration in supabase/migrations/*.sql; do
  echo
  echo "-- ============================================================"
  echo "-- $migration"
  echo "-- ============================================================"
  sed -e "s/<PROJECT_REF>/$REF/g" -e "s/<WEBHOOK_SECRET>/$SECRET/g" "$migration"
done
